---
title: "Data Science Projects"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

<br/>

# Professional Wine Reviews

I have completed a project regarding professional wine reviews with my friends. Please visit the project website for detailed information:

https://congzhang63.github.io/p8105_final_project

<br/>

# Predicting Crime Rate

Together with my friends, I also built machine learning models (lasso regression, ridge regression, elastic net, random forests, etc.) to predict the crime rate within Boston area. Please refer to the project github for detailed information:

https://github.com/ruiyangli1/p8106_final_project

<br/>

# Analyzing COVID-19 in New York City
As a Data Science Institute Scholar (Data Analyst) of the REACH OUT Study, I have created the study population for the project, conducted exploratory data analysis, and now I'm fitting statistical models to evaluate the associations between chronic exposure to air pollution and severity of COVID-19 outcomes and disparities in New York City:

https://github.com/CongZhang63/REACH_OUT_Study_Aim2

